### ISSUE TITLE
Where are the @Preview ?

### ISSUE THREAD

**Issue by gastsail** [exyte/ComposeMultiplatformDribbbleAudio#1]
Hi how are you, I'm also working on a compose multiplatform project, I have found your repo and I'm trying to know how to do Previews on the work I'm doing. This is because I find time consuming compiling the app to see the results.

I have added the tooling preview lib to the androiMain dependencies

![Screen Shot 2023-08-15 at 15 02 21](https://github.com/exyte/ComposeMultiplatformDribbbleAudio/assets/24615408/141d572e-dd6f-44e9-a078-cd80068ae004)

And I can successfully use it on androidMain package

![Screen Shot 2023-08-15 at 15 02 47](https://github.com/exyte/ComposeMultiplatformDribbbleAudio/assets/24615408/9526202e-0685-4f84-8e95-d3f1619b1e6e)

Problem is that the preview is not generated and I cannot see it , do you know why that happens ?

**Comment by AlexYudenkov** [comment]
Hello! Thank you for the question! First of all, in order for Android Studio to understand that we need to enable the preview in our androidMain module, we need to add this flag to our shared `build.gradle` file:
`android {
    buildFeatures {
         compose = true
     }
}`
This will allow us to see a split screen with the design instead of running the preview on an emulator or a real device.
<img width="221" alt="image" src="https://github.com/exyte/ComposeMultiplatformDribbbleAudio/assets/57913130/60132c50-0249-460d-a0e8-d1df78aa1085">

After that, it’s necessary to add two dependencies instead of one, because the _tooling-preview_ dependency is missing some classes:
 `implementation(“androidx.compose.ui:ui-tooling-preview:1.4.3")`
`implementation(“androidx.compose.ui:ui-tooling:1.4.3”)`
After these steps, the previews should start working. If not, try running a project with the latest version of Android Studio (There were some problems with the Flamingo version, but since the Giraffe everything worked as it should).

In any case, you will have difficulties with the composable from the `commonMain` module, because it is inconvenient to write code and preview in the different modules. It’s cool to use the hack that the JetBrains guys suggested: You can use desktop previews in `commonMain` module. I made an example where you can see how to do it: [example](https://github.com/exyte/ComposeMultiplatformDribbbleAudio/commit/6ef3a8bb7b7b553d52bce4af84f70eea25615cf3)
<img width="1074" alt="image" src="https://github.com/exyte/ComposeMultiplatformDribbbleAudio/assets/57913130/6442487d-97c6-483f-8ad6-90ced55f3e9a">
